package com.automation.SeleniumDemo;

import com.microsoft.playwright.*;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

public class PlaywrightDemo {
    public static void main(String[] args) {
        // Safe execution using try-with-resources to close sockets automatically
        try (Playwright playwright = Playwright.create()) {
            
            // Launch standard Chromium browser visible on your desktop
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
            BrowserContext context = browser.newContext();
            Page page = context.newPage();
            
            System.out.println("Launching Playwright Test Session...");
            page.navigate("https://www.saucedemo.com/");
            
            // Automated steps generated by your codegen session
            page.locator("[data-test=\"username\"]").fill("standard_user");
            page.locator("[data-test=\"password\"]").fill("secret_sauce");
            page.locator("[data-test=\"login-button\"]").click();
            
            // Built-in smart assertion
            assertThat(page.locator("[data-test=\"secondary-header\"]")).isVisible();
            
            System.out.println("Playwright execution completed successfully! Login verified.");
        } catch (Exception e) {
            System.err.println("Test failed due to exception: " + e.getMessage());
        }
    }
}